---
kind: pipeline
name: default

steps:
- name: download-dependencies
  image: golang:1.12
  commands:
    # wait for services to be ready.
    - sleep 5
    - go mod download
    - go mod vendor # this is for when the Dockerfile gets built
  environment:
    GO111MODULE: on
    GOPROXY: https://goproxy.io
  volumes:
  - name: cache
    path: /go


- name: build
  image: golang:1.12
  commands:  # build
  - go build main.go
  environment:
    GO111MODULE: on
  when:
    branch:
      - master
    event:
      - push
  volumes:
  - name: cache
    path: /go

- name: docker-latest
  image: plugins/docker
  settings:
    username:
      from_secret: DOCKER_USER
    password:
      from_secret: DOCKER_PASSWORD
    repo: u03013112/ss-config
    tags:
      - latest
    dockerfile: Dockerfile
  when:
    branch:
      - master
    event:
      - push

      
...